### ISSUE TITLE
Server Ready, Client GUI Pending 🚀 

### ISSUE THREAD

**Issue by kubsnn** [kubsnn/TCP-Chat#14]
**Description:**
Server side is good to go! Now, let's focus on giving our client's GUI some love 💬✨

**Tasks:**
- [x] Design the chat window.
- [x] Implement user authentication.
- [x] Implement user searching, inviting and accepting.
- [x] Polish message display and input.
